package ru.iteco.fmhandroid.ui.data;

public class Data {
    public static final String VALID_LOGIN = "login2";
    public static final String VALID_PASSWORD = "password2";
    public static final String UNREGISTER_LOGIN = "preved";
    public static final String UNREGISTER_PASSWORD = "medved";
    public static final String EMPTY_FIELD = "";
    public static final String FIELD_WITH_SPACE = " ";
    public static final String INVALID_LOGIN = "lOgIn2";
    public static final String INVALID_PASSWORD = "PaSswORd2";
    public static final String SQL_INJECTION = "' OR '1'='1";
    public static final String XSS_INJECTION = "<script>alert('XSS')</script>";
    public static final String ANNOUNCEMENT_CATEGORY = "Объявление";
    public static final String BIRTHDAY_CATEGORY = "День рождения";
    public static final String SALARY_CATEGORY = "Зарплата";
    public static final String TRADE_UNION_CATEGORY = "Профсоюз";
    public static final String HOLIDAY_CATEGORY = "Праздник";
    public static final String MASSAGE_CATEGORY = "Массаж";
    public static final String GRATITUDE_CATEGORY = "Благодарность";
    public static final String NEED_HELP_CATEGORY = "Нужна помощь";
    public static final String NEWS_TITLE_TEXT = "UI automated test news № ";
    public static final String DESCRIPTION_TEXT = "The text is generated by the UI automated test";
    public static final String AUTHENTICATION_ERROR_MESSAGE = "Something went wrong. Try again later.";
    public static final String EMPTY_FIELDS_ERROR_MESSAGE = "Login and password cannot be empty";
    public static final String POP_UP_ERROR_MESSAGE = "Fill empty fields";
    public static final String PRIVACY_POLICY_URL = "https://vhospice.org/#/privacy-policy/";
    public static final String TERMS_OF_USE_URL = "https://vhospice.org/#/terms-of-use";
    public static final String CREATING_PAGE_TEXT = "Creating";
    public static final String EDITING_PAGE_TEXT = "Editing";

    private static final String[] QUOTE_TITLES = {
            "«Хоспис для меня - это то, каким должен быть мир.\"",
            "Хоспис в своем истинном понимании - это творчество",
            "“В хосписе не работают плохие люди” В.В. Миллионщикова\"",
            "«Хоспис – это философия, из которой следует сложнейшая наука медицинской помощи умирающим и искусство ухода, в котором сочетается компетентность и любовь» С. Сандерс",
            "Служение человеку с теплом, любовью и заботой",
            "\"Хоспис продлевает жизнь, дает надежду, утешение и поддержку.\"",
            "\"Двигатель хосписа - милосердие плюс профессионализм\"\n" +
                    "А.В. Гнездилов, д.м.н., один из пионеров хосписного движения.",
            "Важен каждый!"
    };
    public static String[] getQuoteTitles() {
        return QUOTE_TITLES;
    }

    public static final String QUOTE_1_DESCRIPTION = "\"Ну, идеальное устройство мира в моих глазах. Где никто не оценивает, никто не осудит, где говоришь, и тебя слышат, где, если страшно, тебя обнимут и возьмут за руку, а если холодно тебя согреют.” Юля Капис, волонтер";
    public static final String QUOTE_2_DESCRIPTION = "Нет шаблона и стандарта, есть только дух, который живет в разных домах по-разному. Но всегда он добрый, любящий и помогающий.";
    public static final String QUOTE_3_DESCRIPTION = "Все сотрудники хосписа - это адвокаты пациента, его прав и потребностей. Поиск путей решения различных задач - это и есть хосписный индивидуальный подход к паллиативной помощи.";
    public static final String QUOTE_4_DESCRIPTION = "“Творчески и осознанно подойти к проектированию опыта умирания. Создать пространство физическое и психологическое, чтобы позволить жизни отыграть себя до конца. И тогда человек не просто уходит с дороги. Тогда старение и умирание могут стать процессом восхождения до самого конца” \n" + "Би Джей Миллер, врач, руководитель проекта \"Дзен-хоспис\"";
    public static final String QUOTE_5_DESCRIPTION = "\"Если пациента нельзя вылечить, это не значит, что для него ничего нельзя сделать. То, что кажется мелочью, пустяком в жизни здорового человека - для пациента имеет огромный смысл.\"";
    public static final String QUOTE_6_DESCRIPTION = "\" Хоспис - это мои новые друзья. Полная перезагрузка жизненных ценностей. В хосписе нет страха и одиночества.\"\n" + "Евгения Белоусова, дочь пациентки Ольги Васильевны";
    public static final String QUOTE_7_DESCRIPTION = "\"Делай добро... А добро заразительно. По-моему, все люди милосердны. Нужно просто говорить с ними об этом, суметь разбудить в них чувство сострадания, заложенное от рождения\" - В.В. Миллионщикова";
    public static final String QUOTE_8_DESCRIPTION = "\"Каждый, кто оказывается в стенах хосписа, имеет огромное значение в жизни хосписа и его подопечных\"";
}
